/**
 * Canonical status vocabularies shared across the backend.
 *
 * The database and API always use these MACHINE enum values.
 * The frontend maps them to human-readable labels for display only.
 * Never store or compare human-readable labels server-side.
 */

const APPLICATION_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  SHORTLISTED: 'SHORTLISTED',
  INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
  SELECTED: 'SELECTED',
  WAITLISTED: 'WAITLISTED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
  CLOSED: 'CLOSED'
};

const APPLICATION_STATUS_VALUES = Object.values(APPLICATION_STATUS);

// Statuses an HR user is allowed to set via the status-update endpoint.
const HR_SETTABLE_STATUSES = [
  APPLICATION_STATUS.SUBMITTED,
  APPLICATION_STATUS.UNDER_REVIEW,
  APPLICATION_STATUS.SHORTLISTED,
  APPLICATION_STATUS.INTERVIEW_SCHEDULED,
  APPLICATION_STATUS.SELECTED,
  APPLICATION_STATUS.WAITLISTED,
  APPLICATION_STATUS.REJECTED,
  APPLICATION_STATUS.CLOSED
];

// Buckets used by reporting.
const REPORT_BUCKETS = {
  shortlisted: [
    APPLICATION_STATUS.SHORTLISTED,
    APPLICATION_STATUS.INTERVIEW_SCHEDULED,
    APPLICATION_STATUS.SELECTED
  ],
  rejected: [APPLICATION_STATUS.REJECTED, APPLICATION_STATUS.CLOSED],
  underReview: [
    APPLICATION_STATUS.SUBMITTED,
    APPLICATION_STATUS.UNDER_REVIEW,
    APPLICATION_STATUS.WAITLISTED
  ]
};

const JOB_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED'
};

const JOB_STATUS_VALUES = Object.values(JOB_STATUS);

module.exports = {
  APPLICATION_STATUS,
  APPLICATION_STATUS_VALUES,
  HR_SETTABLE_STATUSES,
  REPORT_BUCKETS,
  JOB_STATUS,
  JOB_STATUS_VALUES
};
